### ISSUE TITLE
SwitchBot documentation

### ISSUE THREAD

**Issue by AlanMackie** [cagnulein/switchbot_press#1]
Hi,
I have installed your component and HASSIO finds the entity no problem but "pressing" does nothing.

Does the setup require a SwitchBot hub? 

Switchbot works fine via my iphone app but not via HASSIO.

Thanks

Alan

**Comment by cagnulein** [comment]
Hi, no you don't need a hub but you need a Bluetooth adapter connected to your HASS installation

**Comment by AlanMackie** [comment]
Great thanks. That is what I thought. I have a bluetooth adaptor. How do I connect to HASS? I am running it as a virtual machine on a PC.

**Comment by cagnulein** [comment]
First of all you need to connect the adapter into the VM. Which VM are you using? Virtual box? You have to select the adapter in the usb menu

**Comment by AlanMackie** [comment]
yes, using virtual box. I have just added the bluetooth USB device on virtual box and also added the device_tracker:
  - platform: bluetooth_tracker

And restarted my Hass install.

No Joy

I didnt start virtual box...

**Comment by cagnulein** [comment]
Let's have a look into the logs, what did they say?

**Comment by AlanMackie** [comment]
I have restarted the VM.
When I looking in known_devices.yaml my bluetooth speaker is listed. I deleted that from known_devices and restarted HA and it added the speaker back in.

It is the only device listed there. So bluetooth seems to be finding some devices.

switchbot is added as an entity, so that bit is working.

**Comment by cagnulein** [comment]
ok so now please add in your configuration.yaml these lines:

```
logger:
  default: info
  logs:
    switchbot_press: debug
```

and try to press the switchbot from lovelace

**Comment by AlanMackie** [comment]
done that and not showing in the HA log

**Comment by cagnulein** [comment]
Did you restart HASS and did you turn on the entity?

**Comment by cagnulein** [comment]
If yes ,post all the logs. It must be something

**Comment by bezlitza** [comment]
good afternoon. Installed your switch bot integration. It doesn't work. ((I have hassia on a raspberry pi+). I apologize if my English is bad, I use a translator. I am from Russia

**Comment by bezlitza** [comment]
![Скриншот 13-05-2020 165228](https://user-images.githubusercontent.com/60606791/81821812-fcca9c80-953a-11ea-8e1e-f84bc4c4db74.png)
![Скриншот 13-05-2020 165309](https://user-images.githubusercontent.com/60606791/81821814-fd633300-953a-11ea-9736-d3655be7b094.png)

**Comment by cagnulein** [comment]
@bezlitza could you please post some logs? has the raspberry the bluetooth? is it connected to the HASS correctly?

**Comment by bezlitza** [comment]
[logs.txt](https://github.com/cagnulein/switchbot_press/files/4622415/logs.txt)

**Comment by bezlitza** [comment]
Bluetooth is available. There was a bluetooth tracker in the configuration (and it worked). now I will add ble tracker.

**Comment by bezlitza** [comment]
Added ble tracker and didn't help. I have an esp 32 ble gateway. Is it possible to connect to it?

**Comment by cagnulein** [comment]
@bezlitza did you set to debug into the configuration.yaml?
could you please provide the configuration.yaml about the switchbot integration?

**Comment by bezlitza** [comment]
For some reason, my integrations have stopped being deleted. I delete the lines in the configurator, but the device is still there after reboot, but in the unvialiable state

**Comment by bezlitza** [comment]
I installed it. something should be displayed and where?

**Comment by cagnulein** [comment]
@bezlitza you should see the switchbot in the entities

**Comment by bezlitza** [comment]
![image](https://user-images.githubusercontent.com/60606791/81825966-ef63e100-953f-11ea-955e-fb7b9c5c9ee2.png)

**Comment by bezlitza** [comment]
the first three are deleted

**Comment by cagnulein** [comment]
@bezlitza seems fine, so now try to turn it on in the dashboard

**Comment by bezlitza** [comment]
I've tried it a bunch of times. and through lovelace and here. Nothing happens at all. In lovelace the button turns off after a few seconds

**Comment by cagnulein** [comment]
@bezlitza so the plug-in reacts, so please put switchbot_press to debug, give a turn on cycle and post the logs

**Comment by bezlitza** [comment]
[logs.txt](https://github.com/cagnulein/switchbot_press/files/4622840/logs.txt)

**Comment by cagnulein** [comment]
@bezlitza which version of HASS do you have?

**Comment by cagnulein** [comment]
@bezlitza post your configuration.yaml too

**Comment by bezlitza** [comment]
[confyaml.txt](https://github.com/cagnulein/switchbot_press/files/4622904/confyaml.txt)
0.109.6

**Comment by cagnulein** [comment]
@bezlitza i think you have to change in this way in order to have debug log

```
logger:
  default: info
  logs:
    switchbot_press: debug

```

I will check also the log tomorrow, let's try with this configuration and I hope we will see some useful information

**Comment by bezlitza** [comment]
[logs.txt](https://github.com/cagnulein/switchbot_press/files/4624056/logs.txt)
![Скриншот 13-05-2020 215147](https://user-images.githubusercontent.com/60606791/81852721-2350fd80-9564-11ea-8fa0-8f4524fccafa.png)

**Comment by bezlitza** [comment]
thanks

**Comment by bezlitza** [comment]
Thank you very much. your integration started working after manipulating bluetooth on your phone. I manually connected the switch bot and disabled it in the phone settings and everything worked. Now it is controlled from both a smartphone and ha

**Comment by cagnulein** [comment]
@bezlitza strange, i didn't anything on my phone side in order to have HA working. Anyway good job!

**Comment by cagnulein** [comment]
@AlanMackie did you solve the issue? any updates?

**Comment by AlanMackie** [comment]
Thanks for asking. I only had a little time yesterday to try some fixes and won’t have much today either. 
Keen to get it fixed though so will be back in touch. 
Really appreciate all your support. 
    	
    	

    	Regards
Alan Mackie 
    
  




On Thu, May 14, 2020 at 7:07 AM +0100, "cagnulein" <notifications@github.com> wrote:















@AlanMackie did you solve the issue? any updates?

**Comment by bezlitza** [comment]
Good evening. it stopped working again. I don't know why.

**Comment by bezlitza** [comment]
[logs.txt](https://github.com/cagnulein/switchbot_press/files/4630532/logs.txt)

**Comment by cagnulein** [comment]
> [logs.txt](https://github.com/cagnulein/switchbot_press/files/4630532/logs.txt)

i checked the log and i can't find any trace at all of switchbot pressing, are you sure you are asking to press it?

try adding:
```
logger:
  default: info
  logs:
    pyswitchbot: debug
```

**Comment by bezlitza** [comment]
I didn't remove this from the configuration.

**Comment by bezlitza** [comment]
![image](https://user-images.githubusercontent.com/60606791/82020067-1a117f00-9691-11ea-8507-cbd1ccba7325.png)

**Comment by bezlitza** [comment]
[logs.txt](https://github.com/cagnulein/switchbot_press/files/4632714/logs.txt)

**Comment by bezlitza** [comment]
I press. and nothing happens.

**Comment by cagnulein** [comment]
> I press. and nothing happens.

i saw no evidence at all in your log, maybe you're pressing a wrong entity? bluetooth tracker it's still working? maybe the switchbot is too far and only sometime works?

**Comment by bezlitza** [comment]
Just deleted device trackers and put switchbot on raspberry. It doesn't work again.

**Comment by cagnulein** [comment]
> Just deleted device trackers and put switchbot on raspberry. It doesn't work again.

```
logger:
  default: info
  logs:
    pyswitchbot: debug
    switchbot_press: debug
    switchbot: debug
```

You must have something to the logs if you enable all these 3 debug log...
Did you try to search the switchbot from the raspberry with bluetoothctl?

**Comment by bezlitza** [comment]
[logs.txt](https://github.com/cagnulein/switchbot_press/files/4633234/logs.txt)

**Comment by cagnulein** [comment]
> [logs.txt](https://github.com/cagnulein/switchbot_press/files/4633234/logs.txt)

finally something it comes:

```
2020-05-15 11:40:06 DEBUG (SyncWorker_3) [switchbot] Sending command to switchbot 570102
2020-05-15 11:40:06 DEBUG (SyncWorker_3) [switchbot] Connecting to Switchbot...
2020-05-15 11:40:08 DEBUG (SyncWorker_7) [switchbot] Sending command to switchbot 570100
2020-05-15 11:40:08 DEBUG (SyncWorker_7) [switchbot] Connecting to Switchbot...
```

These are command sends to switchbot plugin not switchbot_press plugin, infact these commands are for turn on and turn off, not pressing. I think you've misconfigured the switchbot entity.

Moreover, you have problems also with the switchbot standard plugin, infact:

```
2020-05-15 11:41:51 WARNING (MainThread) [homeassistant.components.switch] Updating switchbot_press switch took longer than the scheduled update interval 0:00:30
2020-05-15 11:41:51 WARNING (MainThread) [homeassistant.components.switch] Updating switchbot switch took longer than the scheduled update interval 0:00:30
```

Both plugins fail to load...

**Comment by bezlitza** [comment]
![image](https://user-images.githubusercontent.com/60606791/82032301-acbb1980-96a3-11ea-8833-45d7fe83a92a.png)
What should I do?

**Comment by cagnulein** [comment]
> ![image](https://user-images.githubusercontent.com/60606791/82032301-acbb1980-96a3-11ea-8833-45d7fe83a92a.png)
> What should I do?

you have to delete the switchbot part, only the first 3 lines must remain!

**Comment by bezlitza** [comment]
[logs.txt](https://github.com/cagnulein/switchbot_press/files/4633826/logs.txt)

**Comment by bezlitza** [comment]
not help. it still doesn't work

**Comment by bezlitza** [comment]
![image](https://user-images.githubusercontent.com/60606791/82041674-38877280-96b1-11ea-8df2-903a13d9d476.png)

**Comment by cagnulein** [comment]
2020-05-15 13:33:34 DEBUG (SyncWorker_14) [switchbot] Sending command to switchbot 570100
2020-05-15 13:33:34 DEBUG (SyncWorker_14) [switchbot] Connecting to Switchbot...

you're still using the switchbot plugin standard! did you restart your HASS after changing the configuration?

**Comment by bezlitza** [comment]
yes. I rebooted, but the objects still have the switchbot. I deleted it

**Comment by bezlitza** [comment]
I tried in another hassio. I was restoring a backup to another memory card a week ago. Now I started it with the old one, but it still didn't work there.

**Comment by cagnulein** [comment]
> yes. I rebooted, but the objects still have the switchbot. I deleted it

570100 is now the press command, so the plugin send the correct command to the switchbot. Could you please try reducing the distance from the adaptor to the switchbot?

**Comment by bezlitza** [comment]
I put on a raspberry switchbot and nothing happens

**Comment by cagnulein** [comment]
> I put on a raspberry switchbot and nothing happens

did you try bluetoothctl as i suggest before?

**Comment by bezlitza** [comment]
how?

**Comment by cagnulein** [comment]
> how?

ssh to the raspberry and from root run bluetoothctl

from there you can scan and inquiries the bluetooth devices

**Comment by bezlitza** [comment]
![image](https://user-images.githubusercontent.com/60606791/82051737-1d256300-96c3-11ea-9509-ae3d73552771.png)

**Comment by cagnulein** [comment]
@bezlitza you're not root. Anyway try with hcitool instead.

**Comment by bezlitza** [comment]
do these comands work in hassio?

**Comment by bezlitza** [comment]
![image](https://user-images.githubusercontent.com/60606791/82052600-98d3df80-96c4-11ea-9edb-50ddf5a75051.png)

**Comment by cagnulein** [comment]
@bezlitza don't you have root access to your raspberry?

**Comment by bezlitza** [comment]
![image](https://user-images.githubusercontent.com/60606791/82053263-be151d80-96c5-11ea-958c-0c29f2250467.png)
Администратор on russian - admin

**Comment by cagnulein** [comment]
@bezlitza https://developers.home-assistant.io/docs/operating-system/debugging/#ssh-access-to-the-host

**Comment by bezlitza** [comment]
I use this plugin. I don't know what I should do. I already use ssh.

**Comment by bezlitza** [comment]
![image](https://user-images.githubusercontent.com/60606791/82054075-0a149200-96c7-11ea-8116-60e30e608db2.png)

**Comment by cagnulein** [comment]
> I use this plugin. I don't know what I should do. I already use ssh.

in that way you login to ssh to HASSIO not to the host.
Anyway this topic is too far from the start, i don't have free time to analyze your entire system :)

You have to understand why yesterday it worked and today nope :(

If you want we could use teamviewer or something else but not for free, sorry :(
