### ISSUE TITLE
Implements Device_state_attributes

### ISSUE THREAD

**Issue by captainqwerty** [cagnulein/switchbot_press#10]
After installing this and on a reboot I get the following warning:

```
Entity switch.switchbot_press (<class 'custom_components.switchbot_press.switch.SwitchBot_press'>) implements device_state_attributes. Please report it to the custom component author.
12:15:10 – (WARNING) helpers/entity.py
```

Expanded:
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:601
First occurred: 12:15:10 (1 occurrences)
Last logged: 12:15:10

Entity switch.switchbot_press (<class 'custom_components.switchbot_press.switch.SwitchBot_press'>) implements device_state_attributes. Please report it to the custom component author.
```

Please close is this is a false warning or anything but thought I would bring it to your attention.

Thank you very much.

**Comment by cagnulein** [comment]
thanks i will this today 

for reference: extra_state_attributes

**Comment by cagnulein** [comment]
@captainqwerty should be ok, please pull it and test it. Thanks

**Comment by captainqwerty** [comment]
> @captainqwerty should be ok, please pull it and test it. Thanks

Thank you very much, I installed via HACS - So how do I update this sorry? Will HACS see the update?

**Comment by cagnulein** [comment]
no i guess you should put this in the custom_components folder

**Comment by captainqwerty** [comment]
> no i guess you should put this in the custom_components folder

Riggghtt no problem - Will try now and let you know the result.

**Comment by captainqwerty** [comment]
Gave it ago and no longer get that warning! Seems to be resolved.

**Comment by cagnulein** [comment]
yeah!
