### ISSUE TITLE
SwitchDevice Deprecated

### ISSUE THREAD

**Issue by caballero600** [cagnulein/switchbot_press#2]
Logger: homeassistant.components.switch
Source: components/switch/__init__.py:123
Integration: Interruptor (documentation, issues)
First occurred: 10:34:01 (1 occurrences)
Last logged: 10:34:01

SwitchDevice is deprecated, modify SwitchBot_press to extend SwitchEntity

**Comment by cagnulein** [comment]
hi @caballero600 yes i'm aware of it. It's just a warning but ok, i will fix it as soon i have time :D
if you want, you can do it yourself and do a pull request!
