### ISSUE TITLE
Question: MacigSwitchBot

### ISSUE THREAD

**Issue by jampem** [cagnulein/switchbot_press#3]
Hello,

Is this familiar? Any change that it work with HA?
https://www.aliexpress.com/item/1005002119288741.html?spm=a2g0o.productlist.0.0.694254328aS4k2&algo_pvid=e5eeec32-f4c2-4dcd-b55c-301e726e4f28&algo_expid=e5eeec32-f4c2-4dcd-b55c-301e726e4f28-2&btsid=0b0a556516142078505282879ed46f&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_

**Comment by cagnulein** [comment]
I don't really know them, sorry
