### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'switchbot_press'.

### ISSUE THREAD

**Issue by SmartHomeFanatic** [cagnulein/switchbot_press#4]
No 'version' key in the manifest file for custom integration 'switchbot_press'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'switchbot_press'

Any plans on updating this?

**Comment by cagnulein** [comment]
argh i don't have the time right now. You could try to do a PR?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 apr 2021 alle ore 11:24 Daniel ***@***.***>
ha scritto:
