### ISSUE TITLE
Multiple SwitchBots

### ISSUE THREAD

**Issue by dennisschumann** [cagnulein/switchbot_press#6]
Hello,

How Do I and more than one switchbot Devices? Can you please provide a sample configuration?

Best regards

**Comment by cagnulein** [comment]
sorry i never tried to use multiple. i have only one. it should follow the same behaviour of the switchbot project

**Comment by dennisschumann** [comment]
I tried:

switch:
 - plattform: switchbot_press
   mac: 'xx'
   mac: 'yy'

But only the last one is working...

**Comment by cagnulein** [comment]
did you try
<pre>
switch:
 - plattform: switchbot_press
   mac: 'xx'
 - plattform: switchbot_press
   mac: 'yy'
</pre>

?

**Comment by dennisschumann** [comment]
Thank you, this is working...
